apiVersion: v1
kind: Service
metadata:
  name: auth-vpn
  namespace: swiggy
spec:
  type: LoadBalancer
  selector:
    app: auth-vpn
  ports:
    - name: vpn
      port: 7777
      targetPort: 7777
      protocol: TCP
    - name: dashboard
      port: 9100
      targetPort: 9100
      protocol: TCP
